#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

strawberryc monitor -d 1 2 3 4 5 6 7 8 9 10

strawberryc config border_width         2
strawberryc config window_gap          12

strawberryc config split_ratio          0.50
strawberryc config borderless_monocle   true
strawberryc config gapless_monocle      true

strawberryc rule -a Zathura state=tiled
